contentDir: '../docs/payment-pfc'
title: 'PostFinance Checkout'
defaultContentLanguageInSubdir: true
DefaultContentLanguage: de

menu:
    shortcuts:
        -
            name: "<i class='fas fa-shopping-cart'></i> Extension Store"
            identifier: "ds"
            url: "https://extensions.terminal42.ch/p/payment-pfc"
            weight: 10
