#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Dotenv\Dotenv;
use Terminal42\ExtensionsDocs\BookApplication;

require __DIR__ . '/vendor/autoload.php';

(new Dotenv())->usePutenv()->loadEnv(__DIR__ . '/.env');

exit((new BookApplication(__DIR__))->run());
