contentDir: '../docs/payment-stripe'
title: 'Stripe Payments'
defaultContentLanguageInSubdir: true
DefaultContentLanguage: en

menu:
    shortcuts:
        -
            name: "<i class='fas fa-shopping-cart'></i> Extension Store"
            identifier: "ds"
            url: "https://extensions.terminal42.ch/p/payment-stripe"
            weight: 10
